[2025-02-09T05:17:31.192+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-09T05:17:31.216+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_songplays manual__2025-02-09T05:17:23.864545+00:00 [queued]>
[2025-02-09T05:17:31.394+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_songplays manual__2025-02-09T05:17:23.864545+00:00 [queued]>
[2025-02-09T05:17:31.395+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-02-09T05:17:31.427+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): MusicStream_load_songplays> on 2025-02-09 05:17:23.864545+00:00
[2025-02-09T05:17:31.450+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1634) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-09T05:17:31.450+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_MusicStreamPipeline', 'MusicStream_load_songplays', 'manual__2025-02-09T05:17:23.864545+00:00', '--job-id', '447', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp7yksde2h']
[2025-02-09T05:17:31.452+0000] {standard_task_runner.py:91} INFO - Job 447: Subtask MusicStream_load_songplays
[2025-02-09T05:17:31.452+0000] {standard_task_runner.py:63} INFO - Started process 1636 to run task
[2025-02-09T05:17:31.511+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_MusicStreamPipeline.MusicStream_load_songplays manual__2025-02-09T05:17:23.864545+00:00 [running]> on host e5529003cf96
[2025-02-09T05:17:31.584+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Le Huynh Thanh Duong' AIRFLOW_CTX_DAG_ID='etl_MusicStreamPipeline' AIRFLOW_CTX_TASK_ID='MusicStream_load_songplays' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T05:17:23.864545+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-09T05:17:23.864545+00:00'
[2025-02-09T05:17:31.585+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-09T05:17:31.665+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-09T05:17:31.665+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etls/load.py", line 81, in load_fact_songplays
    cur.execute(songplay_table_insert, (row.day_key, user_key, song_key, artist_key, row.sessionId, row.userAgent ))
IndexError: tuple index out of range
[2025-02-09T05:17:31.677+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl_MusicStreamPipeline, task_id=MusicStream_load_songplays, execution_date=20250209T051723, start_date=20250209T051731, end_date=20250209T051731
[2025-02-09T05:17:31.687+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 447 for task MusicStream_load_songplays (tuple index out of range; 1636)
[2025-02-09T05:17:31.714+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-09T05:17:31.727+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T05:17:31.729+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
