[2025-02-09T13:33:19.970+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-09T13:33:19.997+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_artist manual__2025-02-09T13:33:15.434827+00:00 [queued]>
[2025-02-09T13:33:20.106+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_artist manual__2025-02-09T13:33:15.434827+00:00 [queued]>
[2025-02-09T13:33:20.107+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-02-09T13:33:20.119+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): MusicStream_load_artist> on 2025-02-09 13:33:15.434827+00:00
[2025-02-09T13:33:20.125+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2275) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-09T13:33:20.126+0000] {standard_task_runner.py:63} INFO - Started process 2278 to run task
[2025-02-09T13:33:20.125+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_MusicStreamPipeline', 'MusicStream_load_artist', 'manual__2025-02-09T13:33:15.434827+00:00', '--job-id', '563', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp7792fu_q']
[2025-02-09T13:33:20.127+0000] {standard_task_runner.py:91} INFO - Job 563: Subtask MusicStream_load_artist
[2025-02-09T13:33:20.161+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_MusicStreamPipeline.MusicStream_load_artist manual__2025-02-09T13:33:15.434827+00:00 [running]> on host e231ebee4370
[2025-02-09T13:33:20.227+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Le Huynh Thanh Duong' AIRFLOW_CTX_DAG_ID='etl_MusicStreamPipeline' AIRFLOW_CTX_TASK_ID='MusicStream_load_artist' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T13:33:15.434827+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-09T13:33:15.434827+00:00'
[2025-02-09T13:33:20.228+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-09T13:33:20.381+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-09T13:33:20.381+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etls/load.py", line 45, in load_dim_artists
    cur.execute(artist_select, (row.artist_id,))
psycopg2.errors.UndefinedColumn: column "longitude" does not exist
LINE 1: SELECT artist_id, name, location, longitude, latitude FROM d...
                                          ^
HINT:  Perhaps you meant to reference the column "dim_artists.longtitude".

[2025-02-09T13:33:20.391+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl_MusicStreamPipeline, task_id=MusicStream_load_artist, execution_date=20250209T133315, start_date=20250209T133319, end_date=20250209T133320
[2025-02-09T13:33:20.399+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 563 for task MusicStream_load_artist (column "longitude" does not exist
LINE 1: SELECT artist_id, name, location, longitude, latitude FROM d...
                                          ^
HINT:  Perhaps you meant to reference the column "dim_artists.longtitude".
; 2278)
[2025-02-09T13:33:20.421+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-09T13:33:20.437+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T13:33:20.441+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
