[2025-02-09T05:22:58.299+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-09T05:22:58.324+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_time manual__2025-02-09T05:22:55.428110+00:00 [queued]>
[2025-02-09T05:22:58.439+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_time manual__2025-02-09T05:22:55.428110+00:00 [queued]>
[2025-02-09T05:22:58.440+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-02-09T05:22:58.451+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): MusicStream_load_time> on 2025-02-09 05:22:55.428110+00:00
[2025-02-09T05:22:58.459+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1742) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-09T05:22:58.461+0000] {standard_task_runner.py:63} INFO - Started process 1744 to run task
[2025-02-09T05:22:58.460+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_MusicStreamPipeline', 'MusicStream_load_time', 'manual__2025-02-09T05:22:55.428110+00:00', '--job-id', '461', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp67b51ou6']
[2025-02-09T05:22:58.462+0000] {standard_task_runner.py:91} INFO - Job 461: Subtask MusicStream_load_time
[2025-02-09T05:22:58.500+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_MusicStreamPipeline.MusicStream_load_time manual__2025-02-09T05:22:55.428110+00:00 [running]> on host e5529003cf96
[2025-02-09T05:22:58.578+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Le Huynh Thanh Duong' AIRFLOW_CTX_DAG_ID='etl_MusicStreamPipeline' AIRFLOW_CTX_TASK_ID='MusicStream_load_time' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T05:22:55.428110+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-09T05:22:55.428110+00:00'
[2025-02-09T05:22:58.579+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-09T05:22:58.641+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-09T05:22:58.642+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etls/load.py", line 12, in load_dim_Time
    cur.execute("DELETE FROM dim_time")
psycopg2.errors.ForeignKeyViolation: update or delete on table "dim_time" violates foreign key constraint "fact_songplays_day_key_fkey" on table "fact_songplays"
DETAIL:  Key (day_key)=(2018110121) is still referenced from table "fact_songplays".

[2025-02-09T05:22:58.650+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl_MusicStreamPipeline, task_id=MusicStream_load_time, execution_date=20250209T052255, start_date=20250209T052258, end_date=20250209T052258
[2025-02-09T05:22:58.661+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 461 for task MusicStream_load_time (update or delete on table "dim_time" violates foreign key constraint "fact_songplays_day_key_fkey" on table "fact_songplays"
DETAIL:  Key (day_key)=(2018110121) is still referenced from table "fact_songplays".
; 1744)
[2025-02-09T05:22:58.675+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-09T05:22:58.692+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T05:22:58.697+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
