[2025-02-09T05:11:13.692+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-09T05:11:13.721+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_songplays manual__2025-02-09T05:11:06.848691+00:00 [queued]>
[2025-02-09T05:11:13.836+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_songplays manual__2025-02-09T05:11:06.848691+00:00 [queued]>
[2025-02-09T05:11:13.837+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-02-09T05:11:13.851+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): MusicStream_load_songplays> on 2025-02-09 05:11:06.848691+00:00
[2025-02-09T05:11:13.857+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1412) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-09T05:11:13.858+0000] {standard_task_runner.py:63} INFO - Started process 1414 to run task
[2025-02-09T05:11:13.857+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_MusicStreamPipeline', 'MusicStream_load_songplays', 'manual__2025-02-09T05:11:06.848691+00:00', '--job-id', '397', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmphzyxahuc']
[2025-02-09T05:11:13.859+0000] {standard_task_runner.py:91} INFO - Job 397: Subtask MusicStream_load_songplays
[2025-02-09T05:11:13.899+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_MusicStreamPipeline.MusicStream_load_songplays manual__2025-02-09T05:11:06.848691+00:00 [running]> on host e5529003cf96
[2025-02-09T05:11:13.970+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Le Huynh Thanh Duong' AIRFLOW_CTX_DAG_ID='etl_MusicStreamPipeline' AIRFLOW_CTX_TASK_ID='MusicStream_load_songplays' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T05:11:06.848691+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-09T05:11:06.848691+00:00'
[2025-02-09T05:11:13.971+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-09T05:11:14.045+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-09T05:11:14.045+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etls/load.py", line 68, in load_fact_songplays
    cur.execute(song_select, (row.song, row.artist, row.length))
psycopg2.errors.UndefinedTable: relation "songs" does not exist
LINE 2:     FROM songs JOIN artists ON songs.artist_id = artists.art...
                 ^

[2025-02-09T05:11:14.054+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl_MusicStreamPipeline, task_id=MusicStream_load_songplays, execution_date=20250209T051106, start_date=20250209T051113, end_date=20250209T051114
[2025-02-09T05:11:14.064+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 397 for task MusicStream_load_songplays (relation "songs" does not exist
LINE 2:     FROM songs JOIN artists ON songs.artist_id = artists.art...
                 ^
; 1414)
[2025-02-09T05:11:14.073+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-09T05:11:14.086+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T05:11:14.459+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
