[2025-02-08T15:24:49.046+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-08T15:24:49.072+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_song manual__2025-02-08T15:24:44.123363+00:00 [queued]>
[2025-02-08T15:24:49.224+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_song manual__2025-02-08T15:24:44.123363+00:00 [queued]>
[2025-02-08T15:24:49.226+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-02-08T15:24:49.239+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): MusicStream_load_song> on 2025-02-08 15:24:44.123363+00:00
[2025-02-08T15:24:49.247+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2784) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T15:24:49.249+0000] {standard_task_runner.py:63} INFO - Started process 2790 to run task
[2025-02-08T15:24:49.247+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_MusicStreamPipeline', 'MusicStream_load_song', 'manual__2025-02-08T15:24:44.123363+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpj81392_d']
[2025-02-08T15:24:49.250+0000] {standard_task_runner.py:91} INFO - Job 283: Subtask MusicStream_load_song
[2025-02-08T15:24:49.291+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_MusicStreamPipeline.MusicStream_load_song manual__2025-02-08T15:24:44.123363+00:00 [running]> on host 35ef1ca6714b
[2025-02-08T15:24:49.372+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Le Huynh Thanh Duong' AIRFLOW_CTX_DAG_ID='etl_MusicStreamPipeline' AIRFLOW_CTX_TASK_ID='MusicStream_load_song' AIRFLOW_CTX_EXECUTION_DATE='2025-02-08T15:24:44.123363+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-08T15:24:44.123363+00:00'
[2025-02-08T15:24:49.375+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-08T15:24:49.542+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-08T15:24:49.542+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etls/load.py", line 50, in load_dim_songs
    cur.execute(songs_table_insert, (row.song_id, row.title, row.artist_id, row.year, row.duration))
psycopg2.errors.UndefinedColumn: column "artist_id" of relation "dim_songs" does not exist
LINE 1: INSERT INTO dim_songs(song_id, title, artist_id, year, durat...
                                              ^

[2025-02-08T15:24:49.553+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl_MusicStreamPipeline, task_id=MusicStream_load_song, execution_date=20250208T152444, start_date=20250208T152449, end_date=20250208T152449
[2025-02-08T15:24:49.565+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 283 for task MusicStream_load_song (column "artist_id" of relation "dim_songs" does not exist
LINE 1: INSERT INTO dim_songs(song_id, title, artist_id, year, durat...
                                              ^
; 2790)
[2025-02-08T15:24:49.583+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-08T15:24:49.601+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T15:24:49.603+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
