[2025-02-09T03:42:26.927+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-09T03:42:26.960+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_transformation_log manual__2025-02-09T03:42:23.250982+00:00 [queued]>
[2025-02-09T03:42:27.108+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_transformation_log manual__2025-02-09T03:42:23.250982+00:00 [queued]>
[2025-02-09T03:42:27.109+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-02-09T03:42:27.125+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): MusicStream_transformation_log> on 2025-02-09 03:42:23.250982+00:00
[2025-02-09T03:42:27.138+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_MusicStreamPipeline', 'MusicStream_transformation_log', 'manual__2025-02-09T03:42:23.250982+00:00', '--job-id', '357', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp0uml0f3m']
[2025-02-09T03:42:27.143+0000] {standard_task_runner.py:91} INFO - Job 357: Subtask MusicStream_transformation_log
[2025-02-09T03:42:27.143+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=243) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-09T03:42:27.144+0000] {standard_task_runner.py:63} INFO - Started process 246 to run task
[2025-02-09T03:42:27.200+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_MusicStreamPipeline.MusicStream_transformation_log manual__2025-02-09T03:42:23.250982+00:00 [running]> on host e5529003cf96
[2025-02-09T03:42:27.301+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Le Huynh Thanh Duong' AIRFLOW_CTX_DAG_ID='etl_MusicStreamPipeline' AIRFLOW_CTX_TASK_ID='MusicStream_transformation_log' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T03:42:23.250982+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-09T03:42:23.250982+00:00'
[2025-02-09T03:42:27.302+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-09T03:42:27.425+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-09T03:42:27.426+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etls/transform.py", line 40, in process_log
    log_data = log_data[['day_key','userId','song', 'artist', 'userAgent', 'sessionId', 'lenght']]
               ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6179, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['lenght'] not in index"
[2025-02-09T03:42:27.441+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl_MusicStreamPipeline, task_id=MusicStream_transformation_log, execution_date=20250209T034223, start_date=20250209T034226, end_date=20250209T034227
[2025-02-09T03:42:27.455+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 357 for task MusicStream_transformation_log ("['lenght'] not in index"; 246)
[2025-02-09T03:42:27.478+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-09T03:42:27.502+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T03:42:27.510+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
