[2025-02-09T13:31:04.745+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-09T13:31:04.781+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_user manual__2025-02-09T13:31:00.514679+00:00 [queued]>
[2025-02-09T13:31:04.947+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_user manual__2025-02-09T13:31:00.514679+00:00 [queued]>
[2025-02-09T13:31:04.947+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-02-09T13:31:04.960+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): MusicStream_load_user> on 2025-02-09 13:31:00.514679+00:00
[2025-02-09T13:31:04.968+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2201) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-09T13:31:04.969+0000] {standard_task_runner.py:63} INFO - Started process 2205 to run task
[2025-02-09T13:31:04.968+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_MusicStreamPipeline', 'MusicStream_load_user', 'manual__2025-02-09T13:31:00.514679+00:00', '--job-id', '555', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpgqrht3bu']
[2025-02-09T13:31:04.970+0000] {standard_task_runner.py:91} INFO - Job 555: Subtask MusicStream_load_user
[2025-02-09T13:31:05.008+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_MusicStreamPipeline.MusicStream_load_user manual__2025-02-09T13:31:00.514679+00:00 [running]> on host e231ebee4370
[2025-02-09T13:31:05.095+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Le Huynh Thanh Duong' AIRFLOW_CTX_DAG_ID='etl_MusicStreamPipeline' AIRFLOW_CTX_TASK_ID='MusicStream_load_user' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T13:31:00.514679+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-09T13:31:00.514679+00:00'
[2025-02-09T13:31:05.096+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-09T13:31:05.280+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-09T13:31:05.280+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etls/load.py", line 30, in load_dim_Users
    if (row.firstname, row.lastname, row.gender, row.level) == existing_user:
        ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Series' object has no attribute 'firstname'. Did you mean: 'firstName'?
[2025-02-09T13:31:05.301+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl_MusicStreamPipeline, task_id=MusicStream_load_user, execution_date=20250209T133100, start_date=20250209T133104, end_date=20250209T133105
[2025-02-09T13:31:05.311+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 555 for task MusicStream_load_user ('Series' object has no attribute 'firstname'; 2205)
[2025-02-09T13:31:05.343+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-09T13:31:05.356+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T13:31:05.358+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
