[2025-02-09T13:34:31.373+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-09T13:34:31.396+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_song manual__2025-02-09T13:34:26.774684+00:00 [queued]>
[2025-02-09T13:34:31.505+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_song manual__2025-02-09T13:34:26.774684+00:00 [queued]>
[2025-02-09T13:34:31.506+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-02-09T13:34:31.515+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): MusicStream_load_song> on 2025-02-09 13:34:26.774684+00:00
[2025-02-09T13:34:31.520+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2326) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-09T13:34:31.521+0000] {standard_task_runner.py:63} INFO - Started process 2328 to run task
[2025-02-09T13:34:31.521+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_MusicStreamPipeline', 'MusicStream_load_song', 'manual__2025-02-09T13:34:26.774684+00:00', '--job-id', '572', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpiavul2e9']
[2025-02-09T13:34:31.522+0000] {standard_task_runner.py:91} INFO - Job 572: Subtask MusicStream_load_song
[2025-02-09T13:34:31.553+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_MusicStreamPipeline.MusicStream_load_song manual__2025-02-09T13:34:26.774684+00:00 [running]> on host e231ebee4370
[2025-02-09T13:34:31.614+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Le Huynh Thanh Duong' AIRFLOW_CTX_DAG_ID='etl_MusicStreamPipeline' AIRFLOW_CTX_TASK_ID='MusicStream_load_song' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T13:34:26.774684+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-09T13:34:26.774684+00:00'
[2025-02-09T13:34:31.615+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-09T13:34:31.775+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-09T13:34:31.775+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etls/load.py", line 62, in load_dim_songs
    cur.execute(song_select, (row.artist_id,))
psycopg2.errors.UndefinedTable: relation "dim_artist" does not exist
LINE 1: SELECT song_id, title, year, duration FROM dim_artist WHERE ...
                                                   ^

[2025-02-09T13:34:31.784+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl_MusicStreamPipeline, task_id=MusicStream_load_song, execution_date=20250209T133426, start_date=20250209T133431, end_date=20250209T133431
[2025-02-09T13:34:31.795+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 572 for task MusicStream_load_song (relation "dim_artist" does not exist
LINE 1: SELECT song_id, title, year, duration FROM dim_artist WHERE ...
                                                   ^
; 2328)
[2025-02-09T13:34:31.815+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-09T13:34:31.831+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T13:34:31.836+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
